
package ir.org.acm.exam.khosrojerdi.wsc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PrinterIranWebserviceService", targetNamespace = "http://webservice.exam.khosrojerdi.acm.org/")//, wsdlLocation = "http://localhost:8084/WebServiceApp/PrinterIranWebservice?wsdl"
public class PrinterIranWebserviceService
    extends Service
{

    private  static URL PRINTERIRANWEBSERVICESERVICE_WSDL_LOCATION;
    private  static WebServiceException PRINTERIRANWEBSERVICESERVICE_EXCEPTION= new WebServiceException(new MalformedURLException());
    private final static QName PRINTERIRANWEBSERVICESERVICE_QNAME = new QName("http://webservice.exam.khosrojerdi.acm.org/", "PrinterIranWebserviceService");

//    static {
//        URL url = null;
//        WebServiceException e = null;
//        try {
//            url = new URL("http://localhost:8084/WebServiceApp/PrinterIranWebservice?wsdl");
//        } catch (MalformedURLException ex) {
//            e = new WebServiceException(ex);
//        }
//        PRINTERIRANWEBSERVICESERVICE_WSDL_LOCATION = url;
//        PRINTERIRANWEBSERVICESERVICE_EXCEPTION = e;
//    }



    public PrinterIranWebserviceService(URL wsdlLocation) {
        super(wsdlLocation, PRINTERIRANWEBSERVICESERVICE_QNAME);
    }

    public PrinterIranWebserviceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRINTERIRANWEBSERVICESERVICE_QNAME, features);
    }

    public PrinterIranWebserviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PrinterIranWebserviceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PrinterInf
     */
    @WebEndpoint(name = "PrinterIranWebservicePort")
    public PrinterInf getPrinterIranWebservicePort() {
        return super.getPort(new QName("http://webservice.exam.khosrojerdi.acm.org/", "PrinterIranWebservicePort"), PrinterInf.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PrinterInf
     */
    @WebEndpoint(name = "PrinterIranWebservicePort")
    public PrinterInf getPrinterIranWebservicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.exam.khosrojerdi.acm.org/", "PrinterIranWebservicePort"), PrinterInf.class, features);
    }

//    private static URL __getWsdlLocation() {
//        if (PRINTERIRANWEBSERVICESERVICE_EXCEPTION!= null) {
//            throw PRINTERIRANWEBSERVICESERVICE_EXCEPTION;
//        }
//        return PRINTERIRANWEBSERVICESERVICE_WSDL_LOCATION;
//    }

}
